---

name: Deploy  # ワークフローの名前

on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest  # ジョブをubuntu-latestランナー上で実行
    name: Deploy
    steps:
      - uses: actions/checkout@v4  # GitHubリポジトリをチェックアウト

      - name: Install dependencies  # 依存モジュールのインストール
        run: |
          cd htmlparser
          npm ci

      - name: Run tests  # テストを実行
        run: |
          cd htmlparser
          npm test

      - name: Format code  # フォーマットを適用
        run: |
          cd htmlparser
          npm run format

      - name: Commit formatted code  # フォーマットを適用したコードをコミット
        run: |
          git config user.name 'GitHub Actions'
          git config user.email "github-actions@example.com"
          git add .
          git commit -m 'style:Format code' || echo 'No changes to commit'

      - name: Push formatted code  # フォーマットを適用したコードをプッシュ
        if: success()  # フォーマットとコミットが成功した場合のみプッシュ
        run: |
          git push

      - name: Deploy
        uses: cloudflare/wrangler-action@v3  # このステップでCloudflareのWrangler Actionを使用
        with:
          apiToken: ${{ secrets.CF_TOKEN }}  # Wrangler Actionに渡す引数（Cloudflareの APIトークン）
          workingDirectory: htmlparser
