name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        cd htmlparser
        npm ci
    - name: Format code
      run: |
        cd htmlparser
        npm run format
    - name: Commit formatted code
      run: |
        git config user.name 'GitHub Actions'
        git config user.email "github-actions@example.com"
        git add .
        git commit -m 'style:Format code' || echo 'No changes to commit'
    - name: Push formatted code
      if: success()
      run: |
        git push

  test:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        cd htmlparser
        npm ci
    - name: Run tests
      run: |
        cd htmlparser
        npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_TOKEN }}
        workingDirectory: htmlparser