---

name: Deploy  # ワークフローの名前

on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest  # ジョブをubuntu-latestランナー上で実行
    name: Deploy
    steps:
      - uses: actions/checkout@v3  # GitHubリポジトリをチェックアウト
      - name: Deploy
        uses: cloudflare/wrangler-action@v3  # このステップでCloudflareのWrangler Actionを使用
        with:
          apiToken: ${{ secrets.CF_TOKEN }}  # Wrangler Actionに渡す引数（Cloudflareの APIトークン）
